os: 
  - osx
  - linux
env:
  global:
    - DISPLAY=:0
sudo: true
language: ruby
cache: bundler
rvm:
  - 2.5.0
  - ruby-head
before_script: 
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install firefox
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      curl -sSL https://rvm.io/mpapis.asc | gpg --import - 
      gpg --import rvm.gpg && rvm get head
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      brew cask install firefox
      chmod +x bin/firefox/geckodriver-v0.20.1-macos/geckodriver
    fi
  - gem install bundler
  - bundler install
script: 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb-run bundle exec rake ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bundle exec rake; fi
  - cat log/selenium.log
matrix:
  allow_failures:
    - os: osx
    - rvm: ruby-head
